### ISSUE TITLE
server create --async error

### ISSUE THREAD

**Issue by gav-** [binarylane/binarylane-cli#46]
`bl server create --async ...` fails with error:
```
ERROR:binarylane.console.__main__:'int' object has no attribute 'to_dict'
Traceback (most recent call last):
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/__main__.py", line 18, in main
    App().run(sys.argv[1:])
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/app.py", line 110, in run
    self.process(parsed)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/app.py", line 82, in process
    return child.runner_type(self._context).run(args)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/runners/command.py", line 161, in run
    self.response(status_code, received)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/runners/actionlink.py", line 20, in response
    super().response(status_code, action_id)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/runners/action.py", line 57, in response
    super().response(status_code, received)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/runners/command.py", line 96, in response
    self._printer.print(received)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/printers/printer.py", line 33, in print
    data = formatter.format_response(response, self.header, fields)
  File "/home/gavin/.local/lib/python3.10/site-packages/binarylane/console/printers/formatter.py", line 39, in format_response
    data += [_flatten(item, True) for item in response.to_dict().items()]
AttributeError: 'int' object has no attribute 'to_dict'
```
`bl version 0.16.0`
`Python 3.10.12`

**Comment by nats** [comment]
Thank you for your report @gav- .  This is resolved in v0.19.0
